/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mvpdemo_utils_NativeHelper */

#ifndef _Included_com_example_mvpdemo_utils_NativeHelper
#define _Included_com_example_mvpdemo_utils_NativeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mvpdemo_utils_NativeHelper
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_mvpdemo_utils_NativeHelper_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
